# Generated by Django 4.0.6 on 2022-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('BSNS', 'business'), ('lux', 'luxury'), ('Twn', 'twin'), ('Slux', 'superluxury')], max_length=4)),
                ('beds', models.IntegerField()),
                ('guests', models.IntegerField()),
            ],
        ),
    ]
