# Generated by Django 4.0.6 on 2022-07-18 20:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BSNS', 'business'), ('lux', 'luxury'), ('Twn', 'twin'), ('Slux', 'superluxury')], max_length=4)),
                ('no', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=datetime.datetime(2022, 7, 18, 23, 22, 16, 188039))),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='core.categories'),
        ),
    ]
