# Generated by Django 4.0.6 on 2022-07-18 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categories_location_remove_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 23, 25, 6, 266960)),
        ),
    ]
