# Generated by Django 4.0.6 on 2022-07-18 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_check_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='category',
            new_name='room_category',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 23, 30, 12, 411618)),
        ),
    ]
