# Generated by Django 4.0.6 on 2022-07-18 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_room_room_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 23, 31, 18, 718289)),
        ),
    ]
