# Generated by Django 4.0.6 on 2022-07-18 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_booking_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 1, 4, 18, 752334)),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel'),
        ),
    ]
