# Generated by Django 4.0.6 on 2022-07-18 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_category_categories_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='no',
        ),
        migrations.AddField(
            model_name='room',
            name='no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 2, 13, 16, 403266)),
        ),
    ]
