# Generated by Django 4.0.6 on 2022-07-18 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_categories_no_room_no_alter_booking_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 2, 30, 13, 278885)),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('BSNS', 'business'), ('lux', 'luxury'), ('Twn', 'twin'), ('Slux', 'superluxury')], max_length=4),
        ),
    ]
