# Generated by Django 4.0.6 on 2022-07-19 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_hotel_name_alter_booking_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 17, 59, 49, 299575)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.hotel'),
        ),
    ]
