# Generated by Django 4.0.6 on 2022-07-19 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_booking_check_in_alter_booking_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 18, 0, 6, 241311)),
        ),
    ]
