# Generated by Django 4.0.6 on 2022-07-19 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_booking_check_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 18, 15, 35, 340802)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(max_length=50),
        ),
    ]
