# Generated by Django 4.0.6 on 2022-07-19 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_hotel_hotel_name_alter_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_branch',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 20, 30, 15, 878132)),
        ),
    ]
